objective:
  - TV2D[data_fit=lsq, delta=0.0, isotropy=anisotropic,reg=0.02]
  - TV2D[data_fit=huber, delta=0.9, isotropy=anisotropic,reg=0.02]
  - TV2D[data_fit=lsq, delta=0.0, isotropy=isotropic,reg=0.02]
  - TV2D[data_fit=huber, delta=0.9, isotropy=isotropic,reg=0.02]
dataset:
  - Cartoon[size_blur=27,std_blur=2.0,std_noise=0.02,subsampling=10,type_lin_op=deblurring]
  - Cartoon[size_blur=27,std_blur=2.0,std_noise=0.3,subsampling=10,type_lin_op=denoising]
  - Deblurring[size_blur=27,std_blur=2.0,std_noise=0.02,subsampling=4]
  - Denoising[std_noise=0.3,subsampling=4]
  - Simulated[size_blur=27,std_blur=2.0,std_noise=0.02,subsampling=4,type_A=deblurring,type_n=laplace]
  - Simulated[size_blur=27,std_blur=2.0,std_noise=0.3,subsampling=4,type_A=denoising,type_n=gaussian]
solver:
  - ADMM[gamma=0.1]
  - Chambolle-Pock PD-split[eta=1.0,ratio=10.0]
  - CondatVu[eta=1.0,ratio=1.0]
  - Dual PGD analysis[alpha=1.0,ratio=10.0,use_acceleration=True]
  - Primal PGD[prox_tv_method=dr, use_acceleration=True]
  - Primal PGD[prox_tv_method=pd, use_acceleration=True]
  - Primal PGD[prox_tv_method=yang, use_acceleration=True]
  - Primal PGD[prox_tv_method=condat, use_acceleration=True]
  - Primal PGD[prox_tv_method=chambolle-pock, use_acceleration=True]
  - Primal PGD[prox_tv_method=kolmogorov, use_acceleration=True]

n-repetitions: 1
timeout: 60
max-runs: 100
