objective:
  - TV2D[data_fit=lsq,isotropy=anisotropic,reg=0.5]
dataset:
  - Simulated[size_blur=27,std_blur=2.0,std_noise=0.3,subsampling=4,type_A=denoising,type_n=gaussian]
solver:
  - CondatVu[eta=1.0,ratio=1.0]
  - Primal PGD[prox_tv_method=dr,use_acceleration=True]
  - Primal PGD[prox_tv_method=pd,use_acceleration=True]

n-repetitions: 1
timeout: 5
