objective:
  - TV2D[data_fit=lsq,delta=0.0,isotropy=isotropic,reg=0.02]
  - TV2D[data_fit=huber,delta=0.9,isotropy=isotropic,reg=0.02]
dataset:
  - Simulated[size_blur=27,std_blur=2.0,std_noise=0.02,subsampling=4,type_A=deblurring,type_n=gaussian]
solver:
  - CondatVu[eta=1.0,ratio=1.0]
  - sporco

n-repetitions: 1
timeout: 200
max-runs: 100
